[package]
name = "himg"
version = "0.1.0"
edition = "2021"
authors = ["James Edwards-Jones <git@jamedjo.co.uk>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
