[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin-clang"
ar = "aarch64-apple-darwin-ar"
ranlib = "aarch64-apple-darwin-ranlib"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin-clang"
ar = "x86_64-apple-darwin-ar"
ranlib = "x86_64-apple-darwin-ranlib"
