module Himg
  VERSION: String

  class Error < StandardError
  end

  def self.render: (
    String html,
    ?width: Integer,
    ?height: Integer,
    ?truncate: bool,
    ?verbose: bool
  ) -> String

  def self.render_to_string: (String html, Hash[string, untyped] options) -> String
end
