---
name: Build gems

on:
  push:
    tags:
      - "v*"
      - "cross-gem/*"
  workflow_dispatch:

jobs:
  source-gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build gem
        run: bundle exec rake build

      - uses: actions/upload-artifact@v4
        with:
          name: source-gem
          path: pkg/*.gem

  linux-gems:
    name: Build Linux gems
    needs: source-gem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/download-artifact@v4
        with:
          name: source-gem

      - run: sudo apt-get update && sudo apt-get install -y libssl-dev

      #- uses: actions-rust-lang/setup-rust-toolchain@v1
      #  with:
      #    cache-workspaces: ./ext/himg -> target

      - run: bundle exec rake compile

      - run: bundle exec rake native gem

      - uses: actions/upload-artifact@v4
        with:
          name: gem-x86_64-linux
          path: '**/*-x86_64-linux.gem'

  #cross-gem:
  #  name: Compile native gem for ${{ matrix.platform }}
  #  runs-on: ubuntu-22.04
  #  needs: ci-data
  #  strategy:
  #    matrix:
  #      platform: ${{ fromJSON(needs.ci-data.outputs.result).supported-ruby-platforms }}
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: ruby/setup-ruby@v1
  #      with:
  #        bundler-cache: true

  #    - uses: oxidize-rb/actions/cross-gem@v1
  #      id: cross-gem
  #      with:
  #        platform: ${{ matrix.platform }}
  #        ruby-versions: ${{ join(fromJSON(needs.ci-data.outputs.result).stable-ruby-versions, ',') }}

  #    - uses: actions/upload-artifact@v4
  #      with:
  #        name: cross-gem-${{ matrix.platform }}
  #        path: ${{ steps.cross-gem.outputs.gem-path }}

