---
name: Build gems

on:
  push:
    tags:
      - "v*"
    branches:
      - "cross-gem/*"
  workflow_dispatch:

jobs:
  native-gem:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86_64-linux
            os: ubuntu-latest
            setup: sudo apt-get update && sudo apt-get install -y libssl-dev

          - platform: x86_64-darwin
            os: macos-latest

          #- platform: arm64-darwin
          #  os: macos-latest
          #  rust-target: aarch64-apple-darwin

          #- platform: aarch64-linux
          #  os: ubuntu-latest
          #  setup: |
          #    sudo apt-get update && sudo apt-get install -y libssl-dev
          #    echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> $GITHUB_ENV
          #  rust-target: aarch64-unknown-linux-gnu

          #- platform: x86_64-linux-musl
          #  os: ubuntu-latest
          #  setup: |
          #    sudo apt-get update && sudo apt-get install -y musl-tools
          #    echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> $GITHUB_ENV
          #  rust-target: x86_64-unknown-linux-musl

          #- platform: aarch64-linux-musl
          #  os: ubuntu-latest
          #  setup: |
          #    sudo apt-get update && sudo apt-get install -y musl-tools
          #    echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> $GITHUB_ENV
          #  rust-target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.os }}
    name: Compile native gem for ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup environment
        if: matrix.setup
        run: ${{ matrix.setup }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust-target || matrix.platform }}

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./ext/himg -> target
          cache-on-failure: true
          key: ${{ matrix.platform }}

      - run: bundle exec rake compile

      - run: bundle exec rake native gem

      - uses: actions/upload-artifact@v4
        with:
          name: native-gem-${{ matrix.platform }}
          path: '**/*-${{ matrix.platform }}.gem'
